

tests:
	node lib/emulator.js samples/tutorial/01-helloworld.js
	node lib/emulator.js samples/tutorial/02-askforinput.js
	node lib/emulator.js samples/tutorial/03-repeatquestion.js
	node lib/emulator.js samples/tutorial/04-changedefaulttimeout.js
	node lib/emulator.js samples/tutorial/05-usespeechvstone.js
	node lib/emulator.js samples/tutorial/06-usespeechandtone.js
	node lib/emulator.js samples/tutorial/07-calltransfer.js	
	node lib/emulator.js samples/tutorial/08-wrongchoice.js
	node lib/emulator.js samples/tutorial/09-eventhandlers-intro.js
	node lib/emulator.js samples/tutorial/10-eventhandlers-badchoices.js	
	node lib/emulator.js samples/tutorial/11-eventhandlers-goodchoices.js
	node lib/emulator.js samples/tutorial/12-eventhandlers-genericonevent.js
	node lib/emulator.js samples/tutorial/13-callerid-reject.js
	node lib/emulator.js samples/tutorial/13-callerid-reject.js --callerID "4075551111"
	node lib/emulator.js samples/tutorial/14-callerid-redirect.js
	node lib/emulator.js samples/tutorial/15-calledid-branching.js
	node lib/emulator.js samples/tutorial/16-collectdigits.js
	node lib/emulator.js samples/tutorial/17-collectmoredigits.js
	node lib/emulator.js samples/tutorial/18-playaudio.js
	node lib/emulator.js samples/tutorial/19-recordaudio.js
	node lib/emulator.js samples/basic-attendant.js
	node lib/emulator.js samples/bidirectional-sms.js --outbound --parameters "toNumber=+33678007800" 
	node lib/emulator.js samples/bidirectional-sms.js --SMS --initialText "yes"
	node lib/emulator.js samples/dial.js
	node lib/emulator.js samples/dice_coin.js
	node lib/emulator.js samples/jabberwocky.js
	node lib/emulator.js samples/outgoingcall.js
	#node lib/emulator.js samples/prompt-record.js
	node lib/emulator.js samples/readcallerid.js
	node lib/emulator.js samples/record-simpleexample.js
	node lib/emulator.js samples/recordtranscribe.js
	node lib/emulator.js samples/sample.js
	node lib/emulator.js samples/say-as-demo.js
	node lib/emulator.js samples/send-sms.js --outbound --parameters "toNumber=+33678007800" "msg=hello friends"
	#node lib/emulator.js samples/transfer.js




