
samples:
	node ../lib/emulator.js tutorial/01-helloworld.js
	node ../lib/emulator.js tutorial/02-askforinput.js
	node ../lib/emulator.js tutorial/03-repeatquestion.js
	node ../lib/emulator.js tutorial/04-changedefaulttimeout.js
	node ../lib/emulator.js tutorial/05-usespeechvstone.js
	node ../lib/emulator.js tutorial/06-usespeechandtone.js
	node ../lib/emulator.js tutorial/07-calltransfer.js	
	node ../lib/emulator.js tutorial/08-wrongchoice.js
	node ../lib/emulator.js tutorial/09-eventhandlers-intro.js
	node ../lib/emulator.js tutorial/10-eventhandlers-badchoices.js	
	node ../lib/emulator.js tutorial/11-eventhandlers-goodchoices.js
	node ../lib/emulator.js tutorial/12-eventhandlers-genericonevent.js
	node ../lib/emulator.js tutorial/13-callerid-reject.js
	node ../lib/emulator.js tutorial/13-callerid-reject.js --callerID "4075551111"
	node ../lib/emulator.js tutorial/14-callerid-redirect.js
	node ../lib/emulator.js tutorial/15-calledid-branching.js
	node ../lib/emulator.js tutorial/16-collectdigits.js
	node ../lib/emulator.js tutorial/17-collectmoredigits.js
	node ../lib/emulator.js tutorial/18-playaudio.js
	node ../lib/emulator.js tutorial/19-recordaudio.js
	node ../lib/emulator.js basic-attendant.js
	node ../lib/emulator.js bidirectional-sms.js --outbound --parameters "toNumber=+33678007800" 
	node ../lib/emulator.js bidirectional-sms.js --SMS --initialText "yes"
	node ../lib/emulator.js dial.js
	node ../lib/emulator.js dice_coin.js
	node ../lib/emulator.js jabberwocky.js
	node ../lib/emulator.js outgoingcall.js
	#node ../lib/emulator.js prompt-record.js
	node ../lib/emulator.js readcallerid.js
	node ../lib/emulator.js record-simpleexample.js
	node ../lib/emulator.js recordtranscribe.js
	node ../lib/emulator.js sample.js
	node ../lib/emulator.js say-as-demo.js
	node ../lib/emulator.js send-sms.js --outbound --parameters "toNumber=+33678007800" "msg=hello friends"
	#node ../lib/emulator.js transfer.js




