
samples:
	tropoready tutorial/01-helloworld.js
	tropoready tutorial/02-askforinput.js
	tropoready tutorial/03-repeatquestion.js
	tropoready tutorial/04-changedefaulttimeout.js
	tropoready tutorial/05-usespeechvstone.js
	tropoready tutorial/06-usespeechandtone.js
	tropoready tutorial/07-calltransfer.js
	tropoready tutorial/08-wrongchoice.js
	tropoready tutorial/09-eventhandlers-intro.js
	tropoready tutorial/10-eventhandlers-badchoices.js
	tropoready tutorial/11-eventhandlers-goodchoices.js
	tropoready tutorial/12-eventhandlers-genericonevent.js
	tropoready tutorial/13-callerid-reject.js
	tropoready tutorial/13-callerid-reject.js --callerID "4075551111"
	tropoready tutorial/14-callerid-redirect.js
	tropoready tutorial/15-calledid-branching.js
	tropoready tutorial/16-collectdigits.js
	tropoready tutorial/17-collectmoredigits.js
	tropoready tutorial/18-playaudio.js
	tropoready tutorial/19-recordaudio.js
	tropoready basic-attendant.js
	tropoready bidirectional-sms.js --outbound --parameters "toNumber=+33678007800"
	tropoready bidirectional-sms.js --SMS --initialText "yes"
	tropoready dial.js
	tropoready dice_coin.js
	tropoready jabberwocky.js
	tropoready outgoingcall.js
	#tropoready prompt-record.js
	tropoready readcallerid.js
	tropoready record-simpleexample.js
	tropoready recordtranscribe.js
	tropoready sample.js
	tropoready say-as-demo.js
	tropoready send-sms.js --outbound --parameters "toNumber=+33678007800" "msg=hello friends"
	#tropoready transfer.js
	tropoready trequest/speak-my-github-stars.js --callerID "+336780078XX"
	tropoready trequest/text-my-github-stars.js --SMS --initialText "CiscoDevNet awesome-ciscospark"




